version: '3'

services:
  app:
    image: diluka/chinese-holidays-ics
    build:
      context: .
      args: 
        - NPM_CONFIG_REGISTRY=https://r.cnpmjs.org
    ports:
      - "3000:3000"
  sut:
    image: curlimages/curl
    command: -sSL --retry 5 --retry-connrefused --retry-delay 30 -I http://app:3000
    depends_on:
      - app