name: Docker Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.test.yml build
    - name: Test image
      run: docker-compose -f docker-compose.test.yml run --rm sut
